name: "☂️ Epic"
description: Wide area of functionality that delivers significant value within an initiative
projects: ["Inthememory/hq"]
# title: ""
labels: []
type: epic
assignees: []
body:
  - type: textarea
    id: purpose
    attributes:
      label: 🌟 Purpose
      description: Explain the problem this EPIC solves and how it will benefit customers
      placeholder: "Describe the user problem, proposed solution, and customer value..."
    validations:
      required: true
  - type: textarea
    id: desired-outcome
    attributes:
      label: 🎯 Desired Outcome  
      description: How to know if this epic is successful?
      placeholder: "Describe what data or behavior would result in a successful landing of this epic."
    validations:
      required: true

  - type: textarea
    id: important-notes
    attributes:
      label: ⚠️ Important Notes
      description: Edge cases, errors to avoid, etc.
      # placeholder: 
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: 🗒️ Notes
      description: Edge cases, errors to avoid, etc.
      # placeholder: 
    validations:
      required: false