name: "🧪 Spike"
description: To explore / investigate a specific uncertain topic
# projects: []
title: "[Spike] "
labels: []
type: spike
assignees: []
body: 
  - type: markdown
    attributes:
      value: |
        ⚠️ Spike should have a clear scope and be completed in a reasonable time frame.
  - type: dropdown
    id: time-box-estimation
    attributes:
      label: "🕒 Time Box Estimation"
      description: How long will this spike take?
      multiple: false
      options:
        - 1 day
        - 2 days
        - 3 days
      default: 0
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: 🌟 Purpose
      description: Explain the problem this TASK solves and how it will benefit the project / team
      # placeholder: ""
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: How to know if this task is successful?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: false

  - type: textarea
    id: important-notes
    attributes:
      label: ⚠️ Important Notes
      description: Edge cases, errors to avoid, etc.
      # placeholder: 
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: 🗒️ Notes
      description: Edge cases, errors to avoid, etc.
      # placeholder: 
    validations:
      required: false