name: "🔨 Task"
description: Use this template for creating task
# projects: []
title: "[Task] "
labels: []
type: task
assignees: []
body: 
  - type: textarea
    id: purpose
    attributes:
      label: 🌟 Purpose
      description: Explain the problem this TASK solves and how it will benefit the project / team
      # placeholder: ""
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: How to know if this task is successful?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: false

  - type: textarea
    id: important-notes
    attributes:
      label: ⚠️ Important Notes
      description: Edge cases, errors to avoid, etc.
      # placeholder: 
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: 🗒️ Notes
      description: Edge cases, errors to avoid, etc.
      # placeholder: 
    validations:
      required: false